/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackoffStrategy : How retry delays grow between attempts.
/// How retry delays grow between attempts.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BackoffStrategy {
    #[serde(rename = "fixed")]
    Fixed,
    #[serde(rename = "linear")]
    Linear,
    #[serde(rename = "exponential")]
    Exponential,

}

impl std::fmt::Display for BackoffStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fixed => write!(f, "fixed"),
            Self::Linear => write!(f, "linear"),
            Self::Exponential => write!(f, "exponential"),
        }
    }
}

impl Default for BackoffStrategy {
    fn default() -> BackoffStrategy {
        Self::Fixed
    }
}

