/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompleteJobRequest : Body for `POST /api/v1/jobs/{id}/complete`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteJobRequest {
    /// The lease token returned by the lease call.
    #[serde(rename = "lease_token")]
    pub lease_token: String,
    /// Handler result, recorded on the job and merged into workflow context.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl CompleteJobRequest {
    /// Body for `POST /api/v1/jobs/{id}/complete`.
    pub fn new(lease_token: String) -> CompleteJobRequest {
        CompleteJobRequest {
            lease_token,
            result: None,
        }
    }
}

