/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJobRequest {
    #[serde(rename = "config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config: Option<Option<Box<models::JobConfigRequest>>>,
    /// Arbitrary JSON object passed to the handler.
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Don't run before this instant (RFC 3339). The job is created immediately but stays invisible to workers until then.
    #[serde(rename = "run_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub run_at: Option<Option<String>>,
    /// The registered task handler to invoke.
    #[serde(rename = "task_name")]
    pub task_name: String,
}

impl CreateJobRequest {
    pub fn new(task_name: String) -> CreateJobRequest {
        CreateJobRequest {
            config: None,
            payload: None,
            run_at: None,
            task_name,
        }
    }
}

