/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCronResponse {
    #[serde(rename = "cron_id")]
    pub cron_id: String,
}

impl CreateCronResponse {
    pub fn new(cron_id: String) -> CreateCronResponse {
        CreateCronResponse {
            cron_id,
        }
    }
}

