/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJobResponse {
    #[serde(rename = "job_id")]
    pub job_id: String,
}

impl CreateJobResponse {
    pub fn new(job_id: String) -> CreateJobResponse {
        CreateJobResponse {
            job_id,
        }
    }
}

