/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkflowResponse {
    #[serde(rename = "workflow_id")]
    pub workflow_id: String,
}

impl CreateWorkflowResponse {
    pub fn new(workflow_id: String) -> CreateWorkflowResponse {
        CreateWorkflowResponse {
            workflow_id,
        }
    }
}

