/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateCronRequest : Request body for creating a cron schedule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCronRequest {
    #[serde(rename = "config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config: Option<Option<Box<models::JobConfig>>>,
    /// 5-field crontab (UTC); 6/7 fields with leading seconds also accepted.
    #[serde(rename = "cron_expr")]
    pub cron_expr: String,
    /// Unique per tenant.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "queue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue: Option<Option<String>>,
    #[serde(rename = "task_name")]
    pub task_name: String,
}

impl CreateCronRequest {
    /// Request body for creating a cron schedule.
    pub fn new(cron_expr: String, name: String, task_name: String) -> CreateCronRequest {
        CreateCronRequest {
            config: None,
            cron_expr,
            name,
            payload: None,
            queue: None,
            task_name,
        }
    }
}

