/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateWorkflowRequest : Request body for creating a workflow. Shared by the builder DSL and the API so callers and SDKs use the same contract.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkflowRequest {
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "steps")]
    pub steps: Vec<models::WorkflowStep>,
}

impl CreateWorkflowRequest {
    /// Request body for creating a workflow. Shared by the builder DSL and the API so callers and SDKs use the same contract.
    pub fn new(name: String, steps: Vec<models::WorkflowStep>) -> CreateWorkflowRequest {
        CreateWorkflowRequest {
            context: None,
            metadata: None,
            name,
            steps,
        }
    }
}

