/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBatchJobsResponse {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "job_ids")]
    pub job_ids: Vec<String>,
}

impl CreateBatchJobsResponse {
    pub fn new(count: i32, job_ids: Vec<String>) -> CreateBatchJobsResponse {
        CreateBatchJobsResponse {
            count,
            job_ids,
        }
    }
}

