/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBatchJobsRequest {
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::CreateJobRequest>,
}

impl CreateBatchJobsRequest {
    pub fn new(jobs: Vec<models::CreateJobRequest>) -> CreateBatchJobsRequest {
        CreateBatchJobsRequest {
            jobs,
        }
    }
}

