/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CronSchedule : A recurring enqueue schedule. Expressions are standard 5-field crontab (`minute hour day-of-month month day-of-week`), evaluated in **UTC**; a 6/7-field form with leading seconds is also accepted.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CronSchedule {
    #[serde(rename = "config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config: Option<Option<Box<models::JobConfig>>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "cron_expr")]
    pub cron_expr: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "last_enqueued_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_enqueued_at: Option<Option<String>>,
    /// Unique per tenant.
    #[serde(rename = "name")]
    pub name: String,
    /// The next instant this schedule fires. Missed occurrences (server down) collapse into at most one catch-up firing.
    #[serde(rename = "next_run_at")]
    pub next_run_at: String,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Queue for the enqueued jobs (the engine default when absent).
    #[serde(rename = "queue_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue_name: Option<Option<String>>,
    #[serde(rename = "task_name")]
    pub task_name: String,
    #[serde(rename = "tenant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
}

impl CronSchedule {
    /// A recurring enqueue schedule. Expressions are standard 5-field crontab (`minute hour day-of-month month day-of-week`), evaluated in **UTC**; a 6/7-field form with leading seconds is also accepted.
    pub fn new(created_at: String, cron_expr: String, enabled: bool, id: String, name: String, next_run_at: String, task_name: String) -> CronSchedule {
        CronSchedule {
            config: None,
            created_at,
            cron_expr,
            enabled,
            id,
            last_enqueued_at: None,
            name,
            next_run_at,
            payload: None,
            queue_name: None,
            task_name,
            tenant_id: None,
        }
    }
}

