/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeadLetter : A dead-lettered job: a terminal failure recorded for inspection and replay. The original job row remains (subject to retention); this entry captures why it died and, once replayed, which fresh job took its place.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeadLetter {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "error_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "queue_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue_name: Option<Option<String>>,
    /// Why the job dead-lettered: `max_attempts_exceeded`, `non_retryable`, or `handler_not_found`.
    #[serde(rename = "reason")]
    pub reason: String,
    /// The fresh job created by the replay.
    #[serde(rename = "replay_job_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub replay_job_id: Option<Option<String>>,
    /// Set once this entry has been replayed; a dead letter replays at most once.
    #[serde(rename = "replayed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub replayed_at: Option<Option<String>>,
    #[serde(rename = "task_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub task_name: Option<Option<String>>,
    #[serde(rename = "tenant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
}

impl DeadLetter {
    /// A dead-lettered job: a terminal failure recorded for inspection and replay. The original job row remains (subject to retention); this entry captures why it died and, once replayed, which fresh job took its place.
    pub fn new(created_at: String, id: i64, job_id: String, reason: String) -> DeadLetter {
        DeadLetter {
            created_at,
            error_message: None,
            id,
            job_id,
            queue_name: None,
            reason,
            replay_job_id: None,
            replayed_at: None,
            task_name: None,
            tenant_id: None,
        }
    }
}

