/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorBody {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl ErrorBody {
    pub fn new(error: String, timestamp: String) -> ErrorBody {
        ErrorBody {
            error,
            timestamp,
        }
    }
}

