/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FailJobRequest : Body for `POST /api/v1/jobs/{id}/fail`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FailJobRequest {
    /// Human-readable failure reason.
    #[serde(rename = "error")]
    pub error: String,
    /// The lease token returned by the lease call.
    #[serde(rename = "lease_token")]
    pub lease_token: String,
    /// Whether the engine may retry (subject to the job's max_retries). Defaults to true; send false for permanent failures (e.g. bad input).
    #[serde(rename = "retryable", skip_serializing_if = "Option::is_none")]
    pub retryable: Option<bool>,
}

impl FailJobRequest {
    /// Body for `POST /api/v1/jobs/{id}/fail`.
    pub fn new(error: String, lease_token: String) -> FailJobRequest {
        FailJobRequest {
            error,
            lease_token,
            retryable: None,
        }
    }
}

