/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthStatus {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl HealthStatus {
    pub fn new(status: String, timestamp: String, version: String) -> HealthStatus {
        HealthStatus {
            status,
            timestamp,
            version,
        }
    }
}

