/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HeartbeatResponse : Response for `POST /api/v1/jobs/{id}/heartbeat`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeartbeatResponse {
    /// The job's current status. `running` means the lease was extended; anything else (`cancelled`, `completed`, ...) means it was not, and the worker should stop working on the job.
    #[serde(rename = "status")]
    pub status: models::JobStatus,
}

impl HeartbeatResponse {
    /// Response for `POST /api/v1/jobs/{id}/heartbeat`.
    pub fn new(status: models::JobStatus) -> HeartbeatResponse {
        HeartbeatResponse {
            status,
        }
    }
}

