/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HeartbeatRequest : Body for `POST /api/v1/jobs/{id}/heartbeat`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeartbeatRequest {
    /// New lease duration in seconds, measured from now (1..=3600).
    #[serde(rename = "extend_secs")]
    pub extend_secs: i32,
    /// The lease token returned by the lease call.
    #[serde(rename = "lease_token")]
    pub lease_token: String,
}

impl HeartbeatRequest {
    /// Body for `POST /api/v1/jobs/{id}/heartbeat`.
    pub fn new(extend_secs: i32, lease_token: String) -> HeartbeatRequest {
        HeartbeatRequest {
            extend_secs,
            lease_token,
        }
    }
}

