/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Job : A single unit of work.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Job {
    #[serde(rename = "completed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<String>>,
    #[serde(rename = "config")]
    pub config: Box<models::JobConfig>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// How many times this job has been claimed (delivered to a worker). Greater than `retry_count + 1` means a lease expired without a report — i.e. a worker crashed mid-run.
    #[serde(rename = "delivery_count", skip_serializing_if = "Option::is_none")]
    pub delivery_count: Option<i32>,
    #[serde(rename = "error_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    /// Client-supplied key that makes job creation idempotent per tenant: re-submitting the same key returns the original job instead of creating a duplicate.
    #[serde(rename = "idempotency_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<Option<String>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// When this job's next retry becomes claimable (mirrors `scheduled_at` while the job is `retrying`; kept for audit/inspection).
    #[serde(rename = "next_retry_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_retry_at: Option<Option<String>>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "queue_name")]
    pub queue_name: String,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "retry_count")]
    pub retry_count: i32,
    /// When the job becomes claimable. `created_at` for immediate jobs, the requested `run_at` for scheduled jobs, and the next backoff instant while retrying — the durable delay lives in the row itself.
    #[serde(rename = "scheduled_at")]
    pub scheduled_at: String,
    #[serde(rename = "started_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::JobStatus,
    #[serde(rename = "task_name")]
    pub task_name: String,
    #[serde(rename = "tenant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "workflow_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<Option<String>>,
    /// The owning workflow step's name (steps are addressed by name).
    #[serde(rename = "workflow_step_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub workflow_step_id: Option<Option<String>>,
}

impl Job {
    /// A single unit of work.
    pub fn new(config: models::JobConfig, created_at: String, id: String, queue_name: String, retry_count: i32, scheduled_at: String, status: models::JobStatus, task_name: String) -> Job {
        Job {
            completed_at: None,
            config: Box::new(config),
            created_at,
            delivery_count: None,
            error_message: None,
            id,
            idempotency_key: None,
            metadata: None,
            next_retry_at: None,
            payload: None,
            queue_name,
            result: None,
            retry_count,
            scheduled_at,
            started_at: None,
            status,
            task_name,
            tenant_id: None,
            workflow_id: None,
            workflow_step_id: None,
        }
    }
}

