/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobConfigRequest : Optional per-job configuration overrides.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobConfigRequest {
    #[serde(rename = "max_retries", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<Option<i32>>,
    /// Higher is claimed first within a queue (ties: oldest first).
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<i32>>,
    /// Override the destination queue.
    #[serde(rename = "queue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue: Option<Option<String>>,
    /// Per-attempt timeout, in seconds.
    #[serde(rename = "timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Option<i64>>,
}

impl JobConfigRequest {
    /// Optional per-job configuration overrides.
    pub fn new() -> JobConfigRequest {
        JobConfigRequest {
            max_retries: None,
            priority: None,
            queue: None,
            timeout: None,
        }
    }
}

