/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobConfig : Per-job execution configuration. All durations are in seconds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobConfig {
    /// Optional jitter in `0.0..=1.0`. `0.1` => +/-10% randomization of each retry delay, which spreads out thundering-herd retries.
    #[serde(rename = "jitter_factor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub jitter_factor: Option<Option<f64>>,
    #[serde(rename = "max_retries")]
    pub max_retries: i32,
    /// Higher is claimed first within a queue; ties break on `scheduled_at`, then `created_at`.
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "retry_backoff", skip_serializing_if = "Option::is_none")]
    pub retry_backoff: Option<models::BackoffStrategy>,
    #[serde(rename = "retry_delay_secs")]
    pub retry_delay_secs: i64,
    #[serde(rename = "retry_max_delay_secs")]
    pub retry_max_delay_secs: i64,
    #[serde(rename = "timeout_secs")]
    pub timeout_secs: i64,
}

impl JobConfig {
    /// Per-job execution configuration. All durations are in seconds.
    pub fn new(max_retries: i32, priority: i32, retry_delay_secs: i64, retry_max_delay_secs: i64, timeout_secs: i64) -> JobConfig {
        JobConfig {
            jitter_factor: None,
            max_retries,
            priority,
            retry_backoff: None,
            retry_delay_secs,
            retry_max_delay_secs,
            timeout_secs,
        }
    }
}

