/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LeasedJob : A job leased to a (possibly remote) worker, together with the lease token needed to heartbeat, complete, or fail it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeasedJob {
    #[serde(rename = "job")]
    pub job: Box<models::Job>,
    /// Opaque, unguessable proof of lease ownership, regenerated on every claim. Pass it back on heartbeat/complete/fail; a stale token (the lease expired and the job was reclaimed) is rejected.
    #[serde(rename = "lease_token")]
    pub lease_token: String,
}

impl LeasedJob {
    /// A job leased to a (possibly remote) worker, together with the lease token needed to heartbeat, complete, or fail it.
    pub fn new(job: models::Job, lease_token: String) -> LeasedJob {
        LeasedJob {
            job: Box::new(job),
            lease_token,
        }
    }
}

