/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LeaseJobsRequest : Body for `POST /api/v1/queues/{queue}/lease`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeaseJobsRequest {
    /// Lease duration in seconds (1..=3600, default 30). Heartbeat to extend.
    #[serde(rename = "lease_secs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lease_secs: Option<Option<i32>>,
    /// Maximum jobs to lease in one call (1..=100, default 1).
    #[serde(rename = "max_jobs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_jobs: Option<Option<i32>>,
    /// Long-poll wait when the queue is empty, in seconds (0..=30, default 0).
    #[serde(rename = "wait_secs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wait_secs: Option<Option<i32>>,
}

impl LeaseJobsRequest {
    /// Body for `POST /api/v1/queues/{queue}/lease`.
    pub fn new() -> LeaseJobsRequest {
        LeaseJobsRequest {
            lease_secs: None,
            max_jobs: None,
            wait_secs: None,
        }
    }
}

