/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDeadLettersResponse {
    #[serde(rename = "dead_letters")]
    pub dead_letters: Vec<models::DeadLetter>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "limit")]
    pub limit: i64,
    #[serde(rename = "offset")]
    pub offset: i64,
    /// Exact total match count; only present when `include_total=true`.
    #[serde(rename = "total", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total: Option<Option<i64>>,
}

impl ListDeadLettersResponse {
    pub fn new(dead_letters: Vec<models::DeadLetter>, has_more: bool, limit: i64, offset: i64) -> ListDeadLettersResponse {
        ListDeadLettersResponse {
            dead_letters,
            has_more,
            limit,
            offset,
            total: None,
        }
    }
}

