/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWorkflowsResponse {
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "limit")]
    pub limit: i64,
    /// Opaque keyset cursor for the next page (present when `has_more`). Pass it back as `cursor` to continue where this page ended; cheaper than deep OFFSET paging.
    #[serde(rename = "next_cursor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<Option<String>>,
    #[serde(rename = "offset")]
    pub offset: i64,
    /// Exact total match count; only present when `include_total=true`.
    #[serde(rename = "total", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total: Option<Option<i64>>,
    #[serde(rename = "workflows")]
    pub workflows: Vec<models::Workflow>,
}

impl ListWorkflowsResponse {
    pub fn new(has_more: bool, limit: i64, offset: i64, workflows: Vec<models::Workflow>) -> ListWorkflowsResponse {
        ListWorkflowsResponse {
            has_more,
            limit,
            next_cursor: None,
            offset,
            total: None,
            workflows,
        }
    }
}

