/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnFailure : What to do with downstream steps when a step fails.
/// What to do with downstream steps when a step fails.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnFailure {
    #[serde(rename = "halt")]
    Halt,
    #[serde(rename = "skip")]
    Skip,
    #[serde(rename = "continue")]
    Continue,

}

impl std::fmt::Display for OnFailure {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Halt => write!(f, "halt"),
            Self::Skip => write!(f, "skip"),
            Self::Continue => write!(f, "continue"),
        }
    }
}

impl Default for OnFailure {
    fn default() -> OnFailure {
        Self::Halt
    }
}

