/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnSuccess : Reserved for future expansion; only `Continue` is meaningful today.
/// Reserved for future expansion; only `Continue` is meaningful today.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnSuccess {
    #[serde(rename = "continue")]
    Continue,

}

impl std::fmt::Display for OnSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Continue => write!(f, "continue"),
        }
    }
}

impl Default for OnSuccess {
    fn default() -> OnSuccess {
        Self::Continue
    }
}

