/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadyStatus {
    #[serde(rename = "status")]
    pub status: String,
}

impl ReadyStatus {
    pub fn new(status: String) -> ReadyStatus {
        ReadyStatus {
            status,
        }
    }
}

