/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatsSnapshot : Plain snapshot of [`EngineStats`].
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsSnapshot {
    #[serde(rename = "jobs_completed")]
    pub jobs_completed: i64,
    #[serde(rename = "jobs_created")]
    pub jobs_created: i64,
    #[serde(rename = "jobs_dead_lettered")]
    pub jobs_dead_lettered: i64,
    #[serde(rename = "jobs_failed")]
    pub jobs_failed: i64,
    #[serde(rename = "jobs_retried")]
    pub jobs_retried: i64,
    #[serde(rename = "workflows_completed")]
    pub workflows_completed: i64,
    #[serde(rename = "workflows_created")]
    pub workflows_created: i64,
    #[serde(rename = "workflows_failed")]
    pub workflows_failed: i64,
}

impl StatsSnapshot {
    /// Plain snapshot of [`EngineStats`].
    pub fn new(jobs_completed: i64, jobs_created: i64, jobs_dead_lettered: i64, jobs_failed: i64, jobs_retried: i64, workflows_completed: i64, workflows_created: i64, workflows_failed: i64) -> StatsSnapshot {
        StatsSnapshot {
            jobs_completed,
            jobs_created,
            jobs_dead_lettered,
            jobs_failed,
            jobs_retried,
            workflows_completed,
            workflows_created,
            workflows_failed,
        }
    }
}

