/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowStepStatesResponse {
    /// One entry per step, in declaration order.
    #[serde(rename = "steps")]
    pub steps: Vec<models::WorkflowStepState>,
}

impl WorkflowStepStatesResponse {
    pub fn new(steps: Vec<models::WorkflowStepState>) -> WorkflowStepStatesResponse {
        WorkflowStepStatesResponse {
            steps,
        }
    }
}

