/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowStepState : Runtime status of one workflow step (the live progress view).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowStepState {
    /// The job executing this step, once one has been scheduled.
    #[serde(rename = "job_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<Option<String>>,
    /// The step's name (its address within the workflow).
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: models::StepStatus,
}

impl WorkflowStepState {
    /// Runtime status of one workflow step (the live progress view).
    pub fn new(name: String, status: models::StepStatus) -> WorkflowStepState {
        WorkflowStepState {
            job_id: None,
            name,
            status,
        }
    }
}

