/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowDiagramResponse {
    /// The diagram document (Mermaid `graph TD`).
    #[serde(rename = "diagram")]
    pub diagram: String,
    /// Diagram source format. Always `mermaid` today.
    #[serde(rename = "format")]
    pub format: String,
}

impl WorkflowDiagramResponse {
    pub fn new(diagram: String, format: String) -> WorkflowDiagramResponse {
        WorkflowDiagramResponse {
            diagram,
            format,
        }
    }
}

