/*
 * QueueFlow API
 *
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowStep : A node in a workflow DAG. Steps are addressed by their unique `name`; `depends_on` lists the names of steps that must complete first.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowStep {
    #[serde(rename = "config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config: Option<Option<Box<models::JobConfig>>>,
    #[serde(rename = "depends_on", skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "on_failure", skip_serializing_if = "Option::is_none")]
    pub on_failure: Option<models::OnFailure>,
    #[serde(rename = "on_success", skip_serializing_if = "Option::is_none")]
    pub on_success: Option<models::OnSuccess>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "task_name")]
    pub task_name: String,
}

impl WorkflowStep {
    /// A node in a workflow DAG. Steps are addressed by their unique `name`; `depends_on` lists the names of steps that must complete first.
    pub fn new(name: String, task_name: String) -> WorkflowStep {
        WorkflowStep {
            config: None,
            depends_on: None,
            metadata: None,
            name,
            on_failure: None,
            on_success: None,
            payload: None,
            task_name,
        }
    }
}

